#Server configuration
server:
  port: 9000


#App configuration
spring:
  application:
    name: donations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




#Starting name of our api endpoints
api:
  prefix: /api/v1